var annotated_dup =
[
    [ "bfelf", "namespacebfelf.html", [
      [ "elf64_ehdr_t", "structbfelf_1_1elf64__ehdr__t.html", "structbfelf_1_1elf64__ehdr__t" ],
      [ "elf64_phdr_t", "structbfelf_1_1elf64__phdr__t.html", "structbfelf_1_1elf64__phdr__t" ],
      [ "elf64_shdr_t", "structbfelf_1_1elf64__shdr__t.html", "structbfelf_1_1elf64__shdr__t" ]
    ] ],
    [ "helpers", "namespacehelpers.html", [
      [ "file_t", "structhelpers_1_1file__t.html", "structhelpers_1_1file__t" ]
    ] ],
    [ "lib", "namespacelib.html", [
      [ "l0e_t", "structlib_1_1l0e__t.html", "structlib_1_1l0e__t" ],
      [ "l1e_t", "structlib_1_1l1e__t.html", "structlib_1_1l1e__t" ],
      [ "l2e_t", "structlib_1_1l2e__t.html", "structlib_1_1l2e__t" ],
      [ "l3e_t", "structlib_1_1l3e__t.html", "structlib_1_1l3e__t" ]
    ] ],
    [ "loader", "namespaceloader.html", [
      [ "debug_ring_t", "structloader_1_1debug__ring__t.html", "structloader_1_1debug__ring__t" ],
      [ "dump_vmm_args_t", "structloader_1_1dump__vmm__args__t.html", "structloader_1_1dump__vmm__args__t" ],
      [ "global_descriptor_table_register_t", "structloader_1_1global__descriptor__table__register__t.html", "structloader_1_1global__descriptor__table__register__t" ],
      [ "interrupt_descriptor_table_register_t", "structloader_1_1interrupt__descriptor__table__register__t.html", "structloader_1_1interrupt__descriptor__table__register__t" ],
      [ "mk_args_t", "structloader_1_1mk__args__t.html", "structloader_1_1mk__args__t" ],
      [ "start_vmm_args_t", "structloader_1_1start__vmm__args__t.html", "structloader_1_1start__vmm__args__t" ],
      [ "state_save_t", "structloader_1_1state__save__t.html", "structloader_1_1state__save__t" ],
      [ "stop_vmm_args_t", "structloader_1_1stop__vmm__args__t.html", "structloader_1_1stop__vmm__args__t" ],
      [ "tss_t", "structloader_1_1tss__t.html", "structloader_1_1tss__t" ]
    ] ],
    [ "mk", "namespacemk.html", [
      [ "ext_pool_t", "classmk_1_1ext__pool__t.html", "classmk_1_1ext__pool__t" ],
      [ "ext_t", "classmk_1_1ext__t.html", "classmk_1_1ext__t" ],
      [ "ext_tcb_t", "structmk_1_1ext__tcb__t.html", "structmk_1_1ext__tcb__t" ],
      [ "general_purpose_regs_t", "structmk_1_1general__purpose__regs__t.html", "structmk_1_1general__purpose__regs__t" ],
      [ "huge_pool_t", "classmk_1_1huge__pool__t.html", "classmk_1_1huge__pool__t" ],
      [ "intrinsic_t", "classmk_1_1intrinsic__t.html", "classmk_1_1intrinsic__t" ],
      [ "invept_descriptor_t", "structmk_1_1invept__descriptor__t.html", "structmk_1_1invept__descriptor__t" ],
      [ "invvpid_descriptor_t", "structmk_1_1invvpid__descriptor__t.html", "structmk_1_1invvpid__descriptor__t" ],
      [ "l0t_t", "structmk_1_1l0t__t.html", "structmk_1_1l0t__t" ],
      [ "l0te_t", "structmk_1_1l0te__t.html", "structmk_1_1l0te__t" ],
      [ "l1t_t", "structmk_1_1l1t__t.html", "structmk_1_1l1t__t" ],
      [ "l1te_t", "structmk_1_1l1te__t.html", "structmk_1_1l1te__t" ],
      [ "l2t_t", "structmk_1_1l2t__t.html", "structmk_1_1l2t__t" ],
      [ "l2te_t", "structmk_1_1l2te__t.html", "structmk_1_1l2te__t" ],
      [ "l3t_t", "structmk_1_1l3t__t.html", "structmk_1_1l3t__t" ],
      [ "l3te_t", "structmk_1_1l3te__t.html", "structmk_1_1l3te__t" ],
      [ "missing_registers_t", "structmk_1_1missing__registers__t.html", "structmk_1_1missing__registers__t" ],
      [ "mk_main_t", "classmk_1_1mk__main__t.html", "classmk_1_1mk__main__t" ],
      [ "page_aligned_bytes_t", "structmk_1_1page__aligned__bytes__t.html", "structmk_1_1page__aligned__bytes__t" ],
      [ "tls_t", "structmk_1_1tls__t.html", "structmk_1_1tls__t" ],
      [ "vm_pool_t", "classmk_1_1vm__pool__t.html", "classmk_1_1vm__pool__t" ],
      [ "vm_t", "classmk_1_1vm__t.html", "classmk_1_1vm__t" ],
      [ "vmcb_t", "structmk_1_1vmcb__t.html", "structmk_1_1vmcb__t" ],
      [ "vmcs_t", "structmk_1_1vmcs__t.html", "structmk_1_1vmcs__t" ],
      [ "vmexit_log_pp_t", "structmk_1_1vmexit__log__pp__t.html", "structmk_1_1vmexit__log__pp__t" ],
      [ "vmexit_log_record_t", "structmk_1_1vmexit__log__record__t.html", "structmk_1_1vmexit__log__record__t" ],
      [ "vmexit_log_t", "classmk_1_1vmexit__log__t.html", "classmk_1_1vmexit__log__t" ],
      [ "vp_pool_t", "classmk_1_1vp__pool__t.html", "classmk_1_1vp__pool__t" ],
      [ "vp_t", "classmk_1_1vp__t.html", "classmk_1_1vp__t" ],
      [ "vs_pool_t", "classmk_1_1vs__pool__t.html", "classmk_1_1vs__pool__t" ],
      [ "vs_t", "classmk_1_1vs__t.html", "classmk_1_1vs__t" ]
    ] ],
    [ "syscall", "namespacesyscall.html", [
      [ "bf_syscall_t", "classsyscall_1_1bf__syscall__t.html", "classsyscall_1_1bf__syscall__t" ],
      [ "gs_t", "structsyscall_1_1gs__t.html", "structsyscall_1_1gs__t" ],
      [ "intrinsic_t", "classsyscall_1_1intrinsic__t.html", "classsyscall_1_1intrinsic__t" ],
      [ "tls_t", "structsyscall_1_1tls__t.html", "structsyscall_1_1tls__t" ],
      [ "vp_pool_t", "classsyscall_1_1vp__pool__t.html", "classsyscall_1_1vp__pool__t" ],
      [ "vp_t", "classsyscall_1_1vp__t.html", "classsyscall_1_1vp__t" ],
      [ "vs_pool_t", "classsyscall_1_1vs__pool__t.html", "classsyscall_1_1vs__pool__t" ],
      [ "vs_t", "classsyscall_1_1vs__t.html", "classsyscall_1_1vs__t" ]
    ] ],
    [ "vmmctl", "namespacevmmctl.html", [
      [ "vmmctl_main", "classvmmctl_1_1vmmctl__main.html", "classvmmctl_1_1vmmctl__main" ]
    ] ],
    [ "bfelf_elf64_ehdr_t", "structbfelf__elf64__ehdr__t.html", "structbfelf__elf64__ehdr__t" ],
    [ "bfelf_elf64_phdr_t", "structbfelf__elf64__phdr__t.html", "structbfelf__elf64__phdr__t" ],
    [ "bfelf_elf64_shdr_t", "structbfelf__elf64__shdr__t.html", "structbfelf__elf64__shdr__t" ],
    [ "code_aliases_t", "structcode__aliases__t.html", "structcode__aliases__t" ],
    [ "debug_ring_t", "structdebug__ring__t.html", "structdebug__ring__t" ],
    [ "dump_vmm_args_t", "structdump__vmm__args__t.html", "structdump__vmm__args__t" ],
    [ "elf_file_t", "structelf__file__t.html", "structelf__file__t" ],
    [ "elf_segment_t", "structelf__segment__t.html", "structelf__segment__t" ],
    [ "global_descriptor_table_register_t", "structglobal__descriptor__table__register__t.html", "structglobal__descriptor__table__register__t" ],
    [ "interrupt_descriptor_table_register_t", "structinterrupt__descriptor__table__register__t.html", "structinterrupt__descriptor__table__register__t" ],
    [ "l0t_t", "structl0t__t.html", "structl0t__t" ],
    [ "l0te_t", "structl0te__t.html", "structl0te__t" ],
    [ "l1t_t", "structl1t__t.html", "structl1t__t" ],
    [ "l1te_t", "structl1te__t.html", "structl1te__t" ],
    [ "l2t_t", "structl2t__t.html", "structl2t__t" ],
    [ "l2te_t", "structl2te__t.html", "structl2te__t" ],
    [ "l3t_t", "structl3t__t.html", "structl3t__t" ],
    [ "l3te_t", "structl3te__t.html", "structl3te__t" ],
    [ "mk_args_t", "structmk__args__t.html", "structmk__args__t" ],
    [ "mutable_span_t", "structmutable__span__t.html", "structmutable__span__t" ],
    [ "pdpt_t", "structpdpt__t.html", "structpdpt__t" ],
    [ "pdpte_t", "structpdpte__t.html", "structpdpte__t" ],
    [ "pdt_t", "structpdt__t.html", "structpdt__t" ],
    [ "pdte_t", "structpdte__t.html", "structpdte__t" ],
    [ "pml4t_t", "structpml4t__t.html", "structpml4t__t" ],
    [ "pml4te_t", "structpml4te__t.html", "structpml4te__t" ],
    [ "pt_t", "structpt__t.html", "structpt__t" ],
    [ "pte_t", "structpte__t.html", "structpte__t" ],
    [ "span_t", "structspan__t.html", "structspan__t" ],
    [ "start_vmm_args_t", "structstart__vmm__args__t.html", "structstart__vmm__args__t" ],
    [ "state_save_t", "structstate__save__t.html", "structstate__save__t" ],
    [ "stop_vmm_args_t", "structstop__vmm__args__t.html", "structstop__vmm__args__t" ],
    [ "tss_t", "structtss__t.html", "structtss__t" ],
    [ "work_on_cpu_callback_args", "structwork__on__cpu__callback__args.html", "structwork__on__cpu__callback__args" ]
];