var dir_1f3e9f63a742c27404bda6ea11f14f64 =
[
    [ "x64", "dir_38fb157c68664fdc35affdde885c9bb1.html", "dir_38fb157c68664fdc35affdde885c9bb1" ],
    [ "call_ext.hpp", "mocks_2call__ext_8hpp_source.html", null ],
    [ "debug_ring_write.hpp", "mocks_2debug__ring__write_8hpp_source.html", null ],
    [ "dispatch_esr.hpp", "mocks_2dispatch__esr_8hpp_source.html", null ],
    [ "dispatch_syscall.hpp", "mocks_2dispatch__syscall_8hpp_source.html", null ],
    [ "dispatch_syscall_bf_callback_op.hpp", "mocks_2dispatch__syscall__bf__callback__op_8hpp_source.html", null ],
    [ "dispatch_syscall_bf_control_op.hpp", "mocks_2dispatch__syscall__bf__control__op_8hpp_source.html", null ],
    [ "dispatch_syscall_bf_debug_op.hpp", "mocks_2dispatch__syscall__bf__debug__op_8hpp_source.html", null ],
    [ "dispatch_syscall_bf_handle_op.hpp", "mocks_2dispatch__syscall__bf__handle__op_8hpp_source.html", null ],
    [ "dispatch_syscall_bf_intrinsic_op.hpp", "mocks_2dispatch__syscall__bf__intrinsic__op_8hpp_source.html", null ],
    [ "dispatch_syscall_bf_mem_op.hpp", "mocks_2dispatch__syscall__bf__mem__op_8hpp_source.html", null ],
    [ "dispatch_syscall_bf_vm_op.hpp", "mocks_2dispatch__syscall__bf__vm__op_8hpp_source.html", null ],
    [ "dispatch_syscall_bf_vp_op.hpp", "mocks_2dispatch__syscall__bf__vp__op_8hpp_source.html", null ],
    [ "dispatch_syscall_bf_vs_op.hpp", "mocks_2dispatch__syscall__bf__vs__op_8hpp_source.html", null ],
    [ "ext_pool_t.hpp", "mocks_2ext__pool__t_8hpp_source.html", null ],
    [ "ext_t.hpp", "mocks_2ext__t_8hpp_source.html", null ],
    [ "huge_pool_t.hpp", "mocks_2huge__pool__t_8hpp_source.html", null ],
    [ "intrinsic_t.hpp", "mocks_2intrinsic__t_8hpp_source.html", null ],
    [ "mk_main_t.hpp", "mocks_2mk__main__t_8hpp_source.html", null ],
    [ "promote.hpp", "mocks_2promote_8hpp_source.html", null ],
    [ "return_to_mk.hpp", "mocks_2return__to__mk_8hpp_source.html", null ],
    [ "serial_write.hpp", "mocks_2serial__write_8hpp_source.html", null ],
    [ "serial_write_c.hpp", "mocks_2serial__write__c_8hpp_source.html", null ],
    [ "vm_pool_t.hpp", "mocks_2vm__pool__t_8hpp_source.html", null ],
    [ "vm_t.hpp", "mocks_2vm__t_8hpp_source.html", null ],
    [ "vmexit_log_record_t.hpp", "mocks_2vmexit__log__record__t_8hpp_source.html", null ],
    [ "vmexit_log_t.hpp", "mocks_2vmexit__log__t_8hpp_source.html", null ],
    [ "vmexit_loop.hpp", "mocks_2vmexit__loop_8hpp_source.html", null ],
    [ "vp_pool_t.hpp", "mocks_2vp__pool__t_8hpp_source.html", null ],
    [ "vp_t.hpp", "mocks_2vp__t_8hpp_source.html", null ],
    [ "vs_pool_t.hpp", "mocks_2vs__pool__t_8hpp_source.html", null ],
    [ "vs_t.hpp", "mocks_2vs__t_8hpp_source.html", null ]
];